"use strict";(()=>{var e={};e.id=954,e.ids=[954],e.modules={53524:e=>{e.exports=require("@prisma/client")},72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},27790:e=>{e.exports=require("assert")},78893:e=>{e.exports=require("buffer")},84770:e=>{e.exports=require("crypto")},17702:e=>{e.exports=require("events")},32615:e=>{e.exports=require("http")},35240:e=>{e.exports=require("https")},86624:e=>{e.exports=require("querystring")},17360:e=>{e.exports=require("url")},21764:e=>{e.exports=require("util")},71568:e=>{e.exports=require("zlib")},21045:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>I,patchFetch:()=>b,requestAsyncStorage:()=>E,routeModule:()=>w,serverHooks:()=>S,staticGenerationAsyncStorage:()=>x});var a={};r.r(a),r.d(a,{POST:()=>D});var i=r(73278),s=r(45002),n=r(54877),l=r(84770),u=r(53524),d=r(6778),o=r(71309),c=r(51104),p=r(74738),m=r(52420),T=r(51639);let h=new Set(Object.values(u.DayType));function y(e){return`${e.getFullYear()}-${String(e.getMonth()+1).padStart(2,"0")}`}function g(e){return!!(e&&/^([01]\d|2[0-3]):[0-5]\d$/.test(e))}function f(e,t,r,a){return r.headers.get("accept")?.includes("application/json")?o.NextResponse.json({error:e},{status:400}):(0,c.d)(r,`/schedule?team=${t}${a?`&month=${y(a)}`:""}`)}async function D(e){let t=await (0,T.o)();if(!["CLUB_ADMIN","STAFF"].includes(t.user.role))return o.NextResponse.json({error:"Only admins and assigned staff can edit team-level planned schedule dates."},{status:403});let r=await e.formData(),a=String(r.get("teamId")??"");if(!await (0,m.u)(t.user,a))return o.NextResponse.json({error:"You can only edit schedules for teams you manage."},{status:403});let i=function(e){let[t,r,a]=e.split("-").map(Number);return t&&r&&a?new Date(t,r-1,a):null}(String(r.get("date")??""));if(!i)return(0,c.d)(e,`/schedule?team=${a}`);let s=String(r.get("dayType")??"REST"),n=h.has(s)?s:u.DayType.REST,D=n.toLowerCase().replaceAll("_"," "),w=String(r.get("title")??"").trim()||D,E=String(r.get("startTime")??"").trim()||null,x=String(r.get("endTime")??"").trim()||null,S=String(r.get("notes")??"").trim()||null,I=String(r.get("repeat")??"none");return g(E)?x&&!g(x)?f("End time is not in a valid schedule time format.",a,e,i):E&&x&&x<=E?f("End time should be later than start time.",a,e,i):("weekly"===I?await p._.$executeRaw`
      INSERT INTO "TeamScheduleDefault" ("id", "teamId", "dayOfWeek", "dayType", "title", "startTime", "endTime", "notes")
      VALUES (${(0,l.randomUUID)()}, ${a}, ${i.getDay()}, CAST(${n} AS "DayType"), ${w}, ${E}, ${x}, ${S})
      ON CONFLICT ("teamId", "dayOfWeek") DO UPDATE SET
        "dayType" = EXCLUDED."dayType",
        "title" = EXCLUDED."title",
        "startTime" = EXCLUDED."startTime",
        "endTime" = EXCLUDED."endTime",
        "notes" = EXCLUDED."notes"
    `:await p._.$executeRaw`
      INSERT INTO "TeamScheduleEntry" ("id", "teamId", "date", "dayType", "title", "startTime", "endTime", "notes", "createdAt", "updatedAt")
      VALUES (${(0,l.randomUUID)()}, ${a}, ${i}, CAST(${n} AS "DayType"), ${w}, ${E}, ${x}, ${S}, NOW(), NOW())
      ON CONFLICT ("teamId", "date") DO UPDATE SET
        "dayType" = EXCLUDED."dayType",
        "title" = EXCLUDED."title",
        "startTime" = EXCLUDED."startTime",
        "endTime" = EXCLUDED."endTime",
        "notes" = EXCLUDED."notes",
        "updatedAt" = NOW()
    `,(0,d.revalidatePath)("/schedule"),(0,d.revalidatePath)("/admin"),(0,d.revalidatePath)("/athlete"),(0,d.revalidatePath)("/parent"),(0,d.revalidatePath)("/library"),(0,c.d)(e,`/schedule?team=${a}&month=${y(i)}`)):f("Start time is required.",a,e,i)}let w=new i.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/schedule/entries/route",pathname:"/api/schedule/entries",filename:"route",bundlePath:"app/api/schedule/entries/route"},resolvedPagePath:"/Users/benschouten/Documents/New project/app/api/schedule/entries/route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:E,staticGenerationAsyncStorage:x,serverHooks:S}=w,I="/api/schedule/entries/route";function b(){return(0,n.patchFetch)({serverHooks:S,staticGenerationAsyncStorage:x})}},16910:(e,t,r)=>{r.d(t,{L:()=>l});var a=r(63506),i=r.n(a),s=r(76214),n=r(74738);let l={session:{strategy:"jwt"},pages:{signIn:"/signin"},providers:[(0,s.Z)({name:"EliteFuel demo account",credentials:{email:{label:"Email",type:"email"},password:{label:"Password",type:"password"}},async authorize(e){if(!e?.email||!e.password)return null;let t=await n._.user.findUnique({where:{email:e.email.toLowerCase()}});return t&&await i().compare(e.password,t.passwordHash)?{id:t.id,email:t.email,name:t.name,role:t.role,clubId:t.clubId}:null}})],callbacks:{jwt:async({token:e,user:t})=>(t&&(e.role=t.role,e.clubId=t.clubId),e),async session({session:e,token:t}){if(e.user){let r="string"==typeof t.email?t.email:"",a=r?await n._.user.findUnique({where:{email:r},select:{id:!0,email:!0,name:!0,role:!0,clubId:!0}}):null;e.user.id=a?.id??t.sub??"",e.user.email=a?.email??e.user.email,e.user.name=a?.name??e.user.name,e.user.role=a?.role??t.role,e.user.clubId=a?.clubId??t.clubId}return e}}}},51104:(e,t,r)=>{r.d(t,{d:()=>i});var a=r(71309);function i(e,t){return e.headers.get("accept")?.includes("application/json")?a.NextResponse.json({ok:!0,redirect:t,message:"Saved"}):a.NextResponse.redirect(new URL(t,e.url),{status:303})}},74738:(e,t,r)=>{r.d(t,{_:()=>i});var a=r(53524);let i=globalThis.prisma??new a.PrismaClient({log:["error"]})},52420:(e,t,r)=>{r.d(t,{t:()=>s,u:()=>i});var a=r(74738);async function i(e,t){return"CLUB_ADMIN"===e.role?!!await a._.team.findFirst({where:{id:t,clubId:e.clubId},select:{id:!0}}):"STAFF"===e.role&&!!await a._.staffTeam.findFirst({where:{userId:e.id,teamId:t,team:{clubId:e.clubId}},select:{id:!0}})}async function s(e,t){return"STAFF"===e.role&&!!await a._.athlete.findFirst({where:{id:t,clubId:e.clubId,team:{staff:{some:{userId:e.id}}}},select:{id:!0}})}},51639:(e,t,r)=>{r.d(t,{o:()=>n,q:()=>l});var a=r(18445),i=r(41288),s=r(16910);async function n(){let e=await (0,a.getServerSession)(s.L);return e?.user||(0,i.redirect)("/signin"),e}function l(e){return"CLUB_ADMIN"===e?"/admin":"STAFF"===e?"/staff":"PARENT"===e?"/parent":"/athlete"}}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[787,143,471,778],()=>r(21045));module.exports=a})();